apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkp-demo-app
  labels:
    app: nkp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nkp-demo
  template:
    metadata:
      labels:
        app: nkp-demo
    spec:
      containers:
        - name: nkp-demo
          image: ghcr.io/virtigon-demos/nkp-ci-cd-template:v202603021150
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1.0"
            - name: BUILD_VERSION
              value: "v202603021150"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "200m"
---

apiVersion: v1
kind: Service
metadata:
  name: nkp-demo-service
spec:
  type: LoadBalancer
  selector:
    app: nkp-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
